---
name: "Tools - Validate YAML Schema"

"on":
  pull_request:
    branches:
      - "main"
    paths:
      - ".yamllint"
      - "**.yaml"
      - "**.yml"
      - "**.yml.example"

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Validate YAML files
        run: yamllint .
