---
name: "Tools - Validate YAML Schema"

"on":
  pull_request:
    branches:
      - "main"
    paths:
      - ".yamllint"
      - "**.yaml"
      - "**.yml"
      - "**.yml.example"

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0

      - name: Validate YAML files
        run: yamllint .
